### ISSUE TITLE
Auth Issue

### ISSUE THREAD

**Issue by pravhjp** [agstrxyz/phpnuxbill-login-hotspot#1]
After click on Login Status it was Sync but send Wrong password for auth to radius.

**Comment by agstrxyz** [comment]
make sure you have http-chap enabled on your mikrotik
![untitled1](https://github.com/user-attachments/assets/3adec0c5-8c41-49cc-85dc-e648d845ac82)

**Comment by pravhjp** [comment]
Thank You  so much
